name: Access EC2 and Install Packages (GitHub-Hosted)

on:
  workflow_dispatch:

jobs:
  install_nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key.pem
          chmod 400 ~/.ssh/github_actions_key.pem  

      - name: Install Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl restart nginx
            sudo systemctl enable nginx
            echo "Nginx installed"
          EOF

  install_tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key.pem
          chmod 400 ~/.ssh/github_actions_key.pem  

      - name: Install Tree on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update
            sudo apt install tree -y
            echo "Tree package installed"
          EOF

  install_mysql:
    runs-on: ubuntu-latest
    needs: install_nginx  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key.pem
          chmod 400 ~/.ssh/github_actions_key.pem  

      - name: Install MySQL on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update
            sudo apt install mysql-server -y
            sudo systemctl restart mysql
            sudo systemctl enable mysql
            echo "MySQL installed"
          EOF
