name: Install Packages on EC2 (GitHub-Hosted)

on:
  workflow_dispatch:

jobs:
  install_nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_URL: ${{ secrets.EC2_HOST }}

      - name: Install Nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl restart nginx
            sudo systemctl enable nginx
            echo "✅ Nginx installed"

  install_tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_URL: ${{ secrets.EC2_HOST }}

      - name: Install Tree
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y tree
            echo "✅ Tree package installed"

  install_mysql:
    runs-on: ubuntu-latest
    needs: install_nginx # Only runs after install_nginx is completed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_URL: ${{ secrets.EC2_HOST }}

      - name: Install MySQL
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y mysql-server
            sudo systemctl restart mysql
            sudo systemctl enable mysql
            echo "✅ MySQL installed"
